[[redirects]]
  from = "/location/*"
  to = "https://www.metaweather.com/api/location/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/forecast/*"
  to = "https://207.148.64.157:8000/:splat"
  status = 200
  force = true
