[[redirects]]
  from = "/location/*"
  to = "https://www.metaweather.com/api/location/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/forecast/*"
  to = "https://seven-timer-https-proxy.herokuapp.com/:splat"
  status = 200
  force = true
